//
//  StringExt.swift
//  Brand
//
//  Created by nada dyaa on 7/10/19.
//  Copyright © 2019 Eslam Dweeb. All rights reserved.
//
import Foundation
import MOLH
extension String {
    static let fontM =  "Avenir-Medium"
    static let fontL = "Avenir-Light"
    static let fontH =  "Avenir-Heavy"
    var localized : String {
        //return NSLocalizedString(self, comment: "")
        return YString.getText(key: self)
    }
}

class YString {
    
    static var productOptions : String { return getText(key: "productOptions") }
    static var itemPrice : String { return getText(key: "itemPrice") }
    static var quantity : String { return getText(key: "quantity") }
    static var totalPrice : String { return getText(key: "totalPrice" ) }
    static var addToCart : String { return getText(key: "addToCart") }
    static var selectOption : String { return getText(key: "selectOption") }
    static var done : String { return getText(key: "done") }
    
    
    static func getText (key : String) -> String {
        
        if MOLHLanguage.currentAppleLanguage().contains("en") {
            return enString[key] ?? key
        }else {
            return arString[key] ?? key
        }
        
    }
    static private let arString : [String : String] = [
        "cart" : "سلة المشتريات",
        "QTY" : "الكميه ",
        "Outofstock" : "نفذ من المتجر",
        "exceeded" : "نفذت الكميه",
        "sar" : "ريال سعودي",
        "Items" : "الكميه: ",
        "Pilling_method" : "طريقه الدفع ",
        "Shippingـmethod" : "طريقه الشحن",
        "Your Addresses" : "عناوينك",
        "Apply Copoun" : "ادخل الكود",
        "Copoun_discount" : "قيمه الخصم",
        "copoun" : "كود",
        "addReview" : "اضف تقيم",
        "Amount" : "الكمية" ,
        "total" : "الاجمالي",
        
        "Confirm" : "تاكيد الطلب",
        "tax" : "ضريبه",
        "Order_Details" : "تفاصيل الطلب",
        "reset" : "اعادة تعيين",
        "There is no Address" : "لا يوجد عنوان",
        "CONTINUE"  : "استمرار",
        "txt_continue"  : "استمرار",
        "PENDING" : "قيد الانتظار",
        "DELIVERED" : "تم التسليم",
        "OTHER" : "غير ذلك",
        "Cancel Order" : "الغاء الطلب",
        "Order_Status" : "حاله الطلب",
        "didn’t_have_Address" :  "ناسف لا يوجد لديك عناوين",
        "Unit price" : "سعر الوحده",
        "Name" : "الاسم",
        "Shipping Method" : "طريقه الشحن",
        "Shipping fee" : "ضريبه الشحن",
        "Billing Method" : "طريقه الدفع",
        "Billing Fee" : "ضريبه الدفع",
        "Order_Items" : "عناصر الطلب",
        "orderNumber" : "رقم الطلب",
        "orderDate" : "تاريخ الطلب",
        "totalAmount" : "الكميه المطلوبه",
        "orderStatus" : "حالة الطلب",
        "allFieldsreq" : " جميع الحقول مطلوبه برجاء ادخل البينات المطلوبه ",
        "invphone" : "رقم هاتف خطا",
        "invpostal" : "رمز بريدي خاطئ يجب ان يكون خمسه ارقام",
        "Invalid City" : "برجاء ادخال مدينه صحيحه",
        "Invalid Person Name" : "اسم المستخدم يجب ان يحتوي علي ثلاثة احرف علي الاقل",
        "Invalid Provider Name" : "برجاء ادخال اسم مزود صحيح" ,
        "Invalid Address Name" : "يجب ان يحتوي العنوان علي ثلاثة احرف علي الاقل",
        "Invalid Email" : "بريد الكتروني خاطئ" ,
        "Empty Bio" : "يجب ادخال سيره ذاتيه ",
        "Empty Phone" : "يجب ادخال رقم هاتف",
        "Empty Address name" : "يجب ادخال عنوان",
        "Empty Person Name" : "يجب ادخال اسم " ,
        "Empty city" : "يجب ادخال مدينه" ,
        "Must Select Your Country" : "يجب اختيار الدوله" ,
        "Must Select Your State" : "يجب اختيار المحافظه",
        "Empty Email" : "يجب ادخال بريد الكتروني ",
        "latitude" : "خطوط العرض يجب ان تكون ارقام",
        "longitude" : "خطوط الطول يجب ان تكون ارقام",
        "latVal" : "خطوط العرض",
        "langVal" : "خطوط الطول",
        
        "camera" : "الكاميرة",
        "mustHavePhoto" : "يجب ان يكون لديك صوره اولاً",
        "myAddresses" : "عناويني",
        "person_name" : "اسم المستخدم",
        "wishlist" : "التمنيات",
        "myOrders" : "طلباتي",
        "myReview" : "تقييمي",
        "language" : "اللغة الحالية",
        "about" : "عنا",
        "terms&privacy" : "الشروط والخصوصية",
        "customerService" : "خدمة العملاء",
        "returnPolicy" : "سياسة العائدات",
        "logout" : "تسجيل الخروج",
        "followus" : "اتبعنا",
        "settings" : "الإعدادات",
        "description" : "التفاصيل",
        "relatedProduct" : "المنتجات ذات صله",
        "seeAll" : "الكل",
        "color" : "الالوان",
        "size" : "الحجم",
        "Shipping_Addresses" : "عنوان الشحن",
        "photo_library" : "مكتبة الصور",
        "app_name" : "BrandsApp",
        "retry" : "اعادة المحاولة",
        "no_internet" : "ﻻ يوجد اتصال بالإنترنت",
        "failed_authenticate_please" : "فشل التوثيق، يرجى المحاولة مرة أخري",
        "explore" : "استكشف",
        "createAccount" : "إنشاء حساب",
        "My addresses" : "عنواني",
        "firstName" : "الأسم الأول",
        "lastName" : "اﻷسم اﻷخير",
        "personName" : "اسم الشخص",
        "phone" : "رقم الجوال",
        "email" : "البريد الإلكتروني",
        "signup" : "أنشئ حساب",
        "already_a_member_login" : "عضو بالفعل؟ ",
        "by_signing_up_you_accept_terms_and_privacy_policy" : "بتسجيل الدخول ، يتم موافقتك علي سياسةالشروط والاحكام  ",
        "login" : "تسجيل الدخول",
        "forgotPassword" : " نسيت كلمة السر؟",
        "email_phone" : "البريدالإلكتروني / الجوال",
        "password" : "كلمة السر",
        "required" : "مطلوب",
        "Add new address" : "اضافة عنوان جديد",
        "phone_not_correct" : "رقم الجوال غير صحيح",
        "email_not_correct" : "البريد الإلكتروني غير صحيح",
        "addresses_book" : "دفتر العناوين",
        "don_t_have_an_acount" : "ليس لديك حساب؟ ",
        "or_login_with" : "أو تسجيل الدخول عبر",
        "please_login_to_continue" : "للإستمرار يرجى تسجيل الدخول",
        
        "forgot_your_password" : "نسيت كلمة السر",
        "enter_your_email_phone_below_to_reset_your_password" : " يرجى إدخال البريد الإلكترونى أو الهاتف لإعادة تعين كلمة السر",
        "new_address" : "عنوان جديد",
        "no_addresses" : "لا يوجد عناوين",
        "new_password" : "كلمة سر جديدة",
        "confirm_new_password" : "أكد كلمة السر الجديدة",
        "request_new_one" : "اطلب واحد جديد",
        "didn_t_receive_a_code" : "لم تستلم رقم تسلسلى؟",
        "please_type_your_new_password" : "من فضلك ادخل كلمة السر الجديدة",
        "we_will_send_you_a_short_code_to_reet_your_password" : "سوف يتم ارسال كود لإعادة ضبط كلمة السر",
        "password_has_been_reset_successfully" : "تم إعادة ضبط كلمة السر بنجاح",
        "address_name" : "اسم العنوان",
        "country" : "الدولة",
        "state" : "المحافظة",
        "city" : "المدينة",
        "detailed_address" : "العنوان بالتفصيل",
        "postal_code" : "الرقم البريدي",
        "location" : "الموقع",
        "lat" : "الطول",
        "lang" : "العرض",
        "pick_location" : "اختر الموقع",
        "confirm" : "تأكيد",
        "edit_address" : "تعديل العنوان",
        "save" : "حفظ",
        "personal_information" : "البيانات الشخصية",
        "personal_info" : "بيانات المستخدم",
        "security_info" : "بيانات الحماية",
        "address_info" : "بيانات العنوان",
        "current_password" : "الرقم السري الحالي",
        "profile" : "المستخدم",
        "birth_date" : "تاريخ الميلاد",
        "gender" : "اختار الجنس",
        "skip" : "تخطي",
        "date" : "التاريخ",
        "reset_password" : "إعادة تعيين كلمة السر",
        "failed_authenticate_lease" : "فشل التوثيق، يرجى المحاولة مرة أخري",
        "set_default" : "تعيين عنوان رئيسي",
        "edit" : "تعديل",
        "delete" : "حذف",
        "cancel" : "إلغاء",
        "email_not_valid" : "بريد الكترونى غير صالح",
        "notification" : "الإشعارات",
        
        "my_reviews" : "تقيماتي",
        "get_started" : "فلنبدأ",
        "Email/phone" : "البريد الالكتروني/ الهاتف",
        "Shipping" : "Shipping",
        "saleInBrand" : "Saled On Brands Sa",
        "buyFromBrand" : "Buy From Brands Sa",
        "recommendedProduct" : "Recommended Products",
        "latestProduct" : "Latest Products",
        "popularProduct" : "Popular Products",
        "flashSale" : "Flash sale",
        "subCategorie" : "subCategorie",
        "browesBy" : "Browse by sub category",
        "stars" : "****************",
        "Checkout_New" : "Checkout New",
        "productOptions" : "خيارات المنتج",
        "itemPrice" : "سعر المنتج",
        "quantity" : "الكمية",
        "totalPrice" : "السعر الكلي" ,
        "addToCart" : "اضف الي العربة",
        "selectOption" : "اختر" ,
        "done" : "تم"

    ]
    
    static private let enString : [String : String] = [
        "cart" : "Cart" ,
        "tax" : "Tax" ,
        "Confirm" : "Confirm & pay" ,
        "total" : "Total" ,
        "addReview" : "Add review" ,
        "copoun" : "Copoun" ,
        "Copoun_discount" : "Copoun discount" ,
        "Apply Copoun" : "Apply Copoun" ,
        "Your Addresses" : "Your Addresses" ,
        "Shippingـmethod" : "Shipping method" ,
        "Shipping_Addresses" : "Shipping Addresses" ,
        "Pilling_method" : "Pilling method" ,
        "Checkout_New" : "Checkout New" ,
        "size" : "Size" ,
        "color" : "Color" ,
        "seeAll" : "See all" ,
        "relatedProduct" : "Related Products" ,
        "description" : "Description" ,
        "Shipping" : "Shipping" ,
        "recommendedProduct" : "Recommended Products" ,
        "flashSale" : "Flash sale" ,
        "latestProduct" : "Latest Products" ,
        "popularProduct" : "Popular Products" ,
        "subCategorie" : "subCategorie" ,
        "browesBy" : "Browse by sub category" ,
        "orderNumber" : "Order Number" ,
        "orderDate" : "Order Date" ,
        "totalAmount" : "Total Amount" ,
        "orderStatus" : "Order Status" ,
        "allFieldsreq" : " All fields are required " ,
        "invphone" : "Invalid Phone number" ,
        "invpostal" : "Postal Code must contain 5 numbers at least " ,
        "Invalid City" : "Invalid City" ,
        "Invalid Person Name" : "person name must contain 3 letters at least" ,
        "Invalid Provider Name" : "Invalid Provider Name"  ,
        "Invalid Address Name" : "Address must be at least 3 characters" ,
        "Invalid Email" : "Invalid Email"  ,
        "Empty Bio" : "Bio field is required" ,
        "Empty Phone" : "Phone number is required" ,
        "Empty Address name" : "Address name is required" ,
        "Empty Person Name" : " Person Name is required"  ,
        "Empty city" : "City Field is required"  ,
        "Must Select Your Country" : "Must Select Your Country"  ,
        "Must Select Your State" : "Must Select Your State" ,
        "Empty Email" : "Email field is required" ,
        "latitude" : "The latitude must be a number" ,
        "latVal" : "latitude" ,
        "longitude" : "The longitude must be a number." ,
        "langVal" : "longitude" ,
        "retry" : "Retry" ,
        "photo_library" : "Photo Library" ,
        "camera" : "Camera" ,
        "person_name" : "Person Name" ,
        "mustHavePhoto" : "You must upload photo first" ,
        "no_internet" : " No internet connection" ,
        "failed_authenticate_please"  : "Failed to authenticate, Please try again" ,
        "explore" : "Explore" ,
        "createAccount" : "Create account" ,
        "firstName" : "First name" ,
        "lastName" : "Last name" ,
        "personName" : "Person name" ,
        "phone" : "Phone" ,
        "phoneNumber" : "Phone Number" ,
        "email" : "Email" ,
        "signup" : "Signup" ,
        "already_a_member_login" : "Already a member?" ,
        "by_signing_up_you_accept_terms_and_privacy_policy" : "By signing up you accept terms and privacy policy" ,
        
        "forgotPassword" : "Forgot password?" ,
        "email_phone" : "Email / Phone" ,
        "password" : "Password" ,
        "required" : "Required" ,
        "phone_not_correct" : "Phone is not correct" ,
        "email_not_correct" : "Email is not correct" ,
        "addresses_book" : "Addresses book" ,
        "don_t_have_an_acount" : "Don\'t have an acount ?" ,
        "or_login_with" : "Or login with" ,
        "please_login_to_continue" : "Please login to continue" ,
        "txt_continue" : "Continue" ,
        "forgot_your_password" : " Forgot your password" ,
        "enter_your_email_phone_below_to_reset_your_password" : "Enter your email/phone below to reset your password" ,
        "new_address" : "New address" ,
        "Add new address" : "Add new address" ,
        "no_addresses" : "No addresses" ,
        "address_name" : "Address name" ,
        "country" : "Country" ,
        "My addresses" : "My addresses" ,
        "state" : "State" ,
        "city" : "City" ,
        "location" : "Location" ,
        "detailed_address" : "Detailed address" ,
        "postal_code" : "Postal code" ,
        "pick_location" : "Pick Location" ,
        "new_password" : "New password" ,
        "confirm_new_password" : "Confirm new password" ,
        "request_new_one" : "Request new one" ,
        "didn_t_receive_a_code" : "Did not receive a code?" ,
        "please_type_your_new_password" : "Please type a new password" ,
        "we_will_send_you_a_short_code_to_reet_your_password" : "We will sent a short code to reset password" ,
        "password_has_been_reset_successfully" : "Password has been reset successfully" ,
        "confirm" : "Confirm" ,
        "edit_address" : "Edit address" ,
        "lat" : "Lat" ,
        "lang" : "Lang" ,
        "save" : "Save" ,
        "personal_information" : "Personal Information" ,
        "personal_info" : "Personal info" ,
        "security_info" : "Security info" ,
        "address_info" : "Address Info" ,
        "stars" : "****************" ,
        "current_password" : "Current password" ,
        "profile" : "Profile" ,
        "birth_date" : "Birth date" ,
        "gender" : "Gender" ,
        "skip" : "Skip" ,
        "reset_password" : "Reset password" ,
        "failed_authenticate_lease" : "Failed to authenticate. Please try again." ,
        "set_default" : "Set default" ,
        "edit" : "Edit" ,
        "delete" : "Delete" ,
        "cancel" : "Cancel" ,
        "email_not_valid" : "Email not valid" ,
        "notification" : "Notification" ,
        
        "my_reviews" : "My Reviews" ,
        "get_started" : "Get Started" ,
        "Email/phone" : "Email/phone" ,
        "CONTINUE" : "CONTINUE" ,
        "There is no Address" : "There is No Address" ,
        "reset" : "Reset" ,
        "date" : "Date" ,
        "Order_Details" : "Order Details" ,
        "Amount" : "Amount" ,
        "Order_Items" : "Order Items" ,
        "Cancelorderafter24" : "* Canceling Order Can not be done after 24 hours ." ,
        "Cancel Order" : "Cancel Order" ,
        "Order_Status" : "Order Status" ,
        "login" : "Login" ,
        "myAddresses" : "My Addresses" ,
        "wishlist" : "Wishlist" ,
        "myOrders" : "My Orders" ,
        "myReview" : "My Review" ,
        "language" : "Current Language" ,
        "about" : "About" ,
        "terms&privacy" : "Terms and Privacy" ,
        "customerService" : "Customer Service" ,
        "returnPolicy" : "Return Policy" ,
        "saleInBrand" : "Saled On Brands Sa" ,
        "buyFromBrand" : "Buy From Brands Sa" ,
        "logout" : "Logout" ,
        "followus" : "Follow us on" ,
        "settings" : "Settings" ,
        "didn’t_have_Address" : "Sorry you didn’t have Address" ,
        "Unit price" : "Unit price" ,
        "Name" : "Name" ,
        "Shipping Method" : "Shipping Method" ,
        "Shipping fee" : "Shipping fee" ,
        "Billing Method" : "Billing Method" ,
        "Billing Fee" : "Billing Fee" ,
        "PENDING" : "PENDING" ,
        "DELIVERED" : "DELIVERED" ,
        "OTHER" : "OTHER" ,
        "Items" : "Items: " ,
        "sar" : "SAR"  ,
        "exceeded" : "Quantity exceeded" ,
        "Outofstock" : "Out of stock" ,
        "QTY" : "QTY" ,
        "productOptions" : "Product options",
        "itemPrice" : "Item price",
        "quantity" : "Quantity",
        "totalPrice" : "Total price" ,
        "addToCart" : "Add to cart",
        "selectOption" : "Select option",
        "done" : "Done"
        
    ]
    
    
    
}
